2024 frame model
CMU-cabot/cabot-arduino-di pull request #2
Opened 2024-07-03 07:19 UTC by leinakanishi

- icomaプロトタイプ，未来館フレームモデル2024:1/2号機で別ブランチ（IMUの取付向が異なる）となっていたため，以下のようにビルドに`-m`オプションを追加しました
```
host $ docker-compose build
host $ docker-compose run arduino
docker $ ./build.sh -m I1 all #icomaプロトタイプ（cabot3-i1）の場合
docker $ ./build.sh -m M1 all #未来館フレームモデル2024:1号機（cabot3-m1）の場合 
docker $ ./build.sh -m M2 all #未来館フレームモデル2024:2号機（cabot3-m2）の場合 
```

2024-07-03 11:29 UTC, daisukes requested changes
基本的には良いと思いますが、IMUReader1/Mは全体を切り替えるのではなく、パラメーターで切り替えるようにしたいです（ほぼ同じコードなので）

Mの方にはIMUのリセットがないのは意図通りでしょうか？

2024-07-04 00:06 UTC, leinakanishi commented
@daisukes 
ご確認ありがとうございます．

> 基本的には良いと思いますが、IMUReader1/Mは全体を切り替えるのではなく、パラメーターで切り替えるようにしたいです（ほぼ同じコードなので）

そうですよね，その書き方が分からず今の構成になっています...
@KenichiroSameshima 
.inoファイル内で条件分岐させることできるでしょうか？
見当がついていないのでアドバイスいただけると助かります．



また，cabot3-m1,m2に関しては，
@muratams さんよりリセット不要とのことだったので以下の部分は削除しています．
https://github.com/CMU-cabot/cabot-arduino-di/blob/f1902eda7d6203735faa95e5da2e214c00cc0897/IMUReaderI1.cpp#L42-L47

2024-07-04 01:26 UTC, daisukes commented
@leinakanishi 

https://github.com/CMU-cabot/cabot-arduino-di/tree/daisukes/2024-frame-model-fix

こちらで動くか確認していただけますか？

2024-07-04 08:22 UTC, leinakanishi commented
@daisukes 
ありがとうございます，お手数おかけしてすみません．
来週金曜の未来館出社時に確認します．

2024-07-05 07:55 UTC, KenichiroSameshima commented
@leinakanishi 
> .inoファイル内で条件分岐させることできるでしょうか？
> 見当がついていないのでアドバイスいただけると助かります．

.inoファイルの中で条件分岐するよりも、[IMUReader.cppの中で切り替える](https://github.com/CMU-cabot/cabot-arduino-di/blob/sameshima/2024-frame-model-fix/IMUReader.cpp#L42-L63)方が良いように思います。

上記コードを、ACE22で動作確認しました。```./build.sh -m I1 all```の場合と```./build.sh -m M1 all```の場合で、```/cabot/imu/data```の値が正負反転していたので、切替には成功しているみたいです。

2024-07-05 08:30 UTC, leinakanishi commented
@KenichiroSameshima 
ご対応いただきありがとうございます．
.cpp側にも引数を渡せるんですね...勉強になりました．
来週金曜の未来館出社時に動作確認します．

2024-07-12 09:19 UTC, leinakanishi commented
@daisukes @KenichiroSameshima 
cabot3-m2（未来館フレームモデル2024:2）にて以下手順で動作確認しました．
https://app.box.com/notes/1546746702627

cabot-driversをmainブランチ，cabot-arduino-diを[daisukes/2024-frame-model-fix](https://github.com/CMU-cabot/cabot-arduino-di/tree/daisukes/2024-frame-model-fix)ではディスク動作ok，LRA動作okでした．

cabot-driversをmainブランチ，cabot-arduino-diを[sameshima/2024-frame-model-fix](https://github.com/CMU-cabot/cabot-arduino-di/tree/sameshima/2024-frame-model-fix)ではディスク動作okですが，以下コマンド実行時にLRAの振動が止まりませんでした．`"data: 0"`を送ると止まりました．
`ros2 topic pub -1 /vibrator1 std_msgs/msg/UInt8 "data: 10"  `

`/vibrator3`, `/vibrator4`トピックにメッセージを送った際は振動は一瞬だけでした．

こちらのプルリクはマージせずにcloseした，[daisukes/2024-frame-model-fix](https://github.com/CMU-cabot/cabot-arduino-di/tree/daisukes/2024-frame-model-fix)ブランチから`ros2`ブランチへのプルリク出した方がいいでしょうか？

2024-07-12 12:17 UTC, daisukes commented
すいません、daisukes/2024-model-fixにコミットしたつもりができていませんでした…。

- https://github.com/CMU-cabot/cabot-arduino-di/commit/30b9d8e7d89e9d8cb41a8e8dc0ee383d1c1dace0


> cabot-driversをmainブランチ，cabot-arduino-diを[sameshima/2024-frame-model-fix](https://github.com/CMU-cabot/cabot-arduino-di/tree/sameshima/2024-frame-model-fix)ではディスク動作okですが，以下コマンド実行時にLRAの振動が止まりませんでした．`"data: 0"`を送ると止まりました． `ros2 topic pub -1 /vibrator1 std_msgs/msg/UInt8 "data: 10" `

毎回起こるわけではないですよね？
であれば、こちらはブランチの問題というよりかは、ESP32 <-> ちびマイコン間のシリアル通信の問題だと思います。

- https://github.com/CMU-cabot/cabot-arduino-ace/pull/12

このPRと同じような処理をこちらにも実装する必要があると思います。


> こちらのプルリクはマージせずにcloseし，[daisukes/2024-frame-model-fix](https://github.com/CMU-cabot/cabot-arduino-di/tree/daisukes/2024-frame-model-fix)ブランチからros2ブランチへのプルリク出した方がいいでしょうか？

こちらはクローズせずに、この2024-frame-modelにどちらかをマージしてpushすれば、このPRに反映されます。

2024-08-07 03:30 UTC, leinakanishi commented
@KenichiroSameshima @daisukes 
https://github.com/CMU-cabot/cabot-arduino-di/pull/2/commits/6fe51469ac3c89763f4612569acb49de0a70d8f6 を2024-frame-modelにmergeして実機（cabot3-m2）にて動作確認okでした．

ハンドル単体テスト・cabot起動の両方でLRAの振動・ディスク・IMUデータ取得okでした．

2024-08-07 04:18 UTC, KenichiroSameshima approved these changes

2024-08-07 04:18 UTC, KenichiroSameshima commented on README.md
"-m ACE"に関する記述が抜けているので、これからコミットいたします。

2024-08-07 04:21 UTC, KenichiroSameshima commented on README.md
@leinakanishi 
対応終わりました。
実機(cabot3-m2)での動作確認OKだったので、mainブランチとマージしても問題ないかと思います。

2024-08-07 04:26 UTC, leinakanishi commented on README.md
ありがとうございました！レビュー後にマージします．

2024-08-07 04:27 UTC, leinakanishi commented
@daisukes 
お待たせしており申し訳ありません，実機にて動作確認取れましたのでお手隙の際にレビューのapprove
をお願いします．

2024-08-07 05:13 UTC, daisukes commented
いくつかのファイルの改行コードがCRLFになっていたので修正しました

2024-08-07 05:24 UTC, daisukes approved these changes

2024-08-07 05:25 UTC, merged